OUTPUT_DIR: 'outputs/UaDAN_Voc2Clipart'
MODEL:
  ENT_WEIGHTED_ON_RCNN_INTER: True
  ENT_WEIGHTED_ON_RPN: True
  ENT_WEIGHTED_ON: True
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: False
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DOMAIN_ADAPTATION_ON: True
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
  DA_HEADS:
    DA_IMG_LOSS_WEIGHT: 1.0
    DA_INS_LOSS_WEIGHT: 1.0
    DA_IMG_GRL_WEIGHT: 0.1
    DA_INS_GRL_WEIGHT: 0.1
DATALOADER:
  SIZE_DIVISIBILITY: 32
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2012_train")
  SOURCE_TRAIN: ("voc_2007_train", "voc_2012_train")
  TARGET_TRAIN: ("clipart_train_voc",)
  TEST: ("clipart_test_voc",)
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1200
SOLVER:
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (50000,)
  MAX_ITER: 70000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1
